id: c70c3a5a54e0470d86df1f27fcfb340a
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_184-Teaching_the_Practice_of_a_Bodhisattva-v2
  language: bo
  author: ''
  volume: {}
